# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat_Firebase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  # Pods for Chat_Firebase

end
